version: '3'
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  backend_spring:
    container_name: spring_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - sqlite3
    networks:
      - net
      
networks:
  net:
    driver: bridge